### PR TITLE
Fix JSON export/import

### LINKED ISSUE #5622: [BUG] PHP Fatal error: Uncaught TypeError sanitizeHTML(): Argument #1 ($data)
**Describe the bug**
Exported feeds with cli/export-zip-for-user.php
Try to import with cli/import-for-user.php to another user

Result in console

> `\cli\import-for-user.php" --user User --filename "file.zip"
>     FreshRSS importing ZIP/OPML/JSON for user “User”…
> 
>     Fatal error: Uncaught TypeError: sanitizeHTML(): Argument https://github.com/FreshRSS/FreshRSS/issues/1 ($data) must be of type string, array given, called in W:\domains\loca
>     lhost\fresh\f1\app\Controllers\importExportController.php on line 442 and defined in W:\domains\localhost\fresh\f1\lib\lib_rss.php:
>     334
>     Stack trace:
>     #0 W:\domains\localhost\fresh\f1\app\Controllers\importExportController.php(442): sanitizeHTML()
>     https://github.com/FreshRSS/FreshRSS/issues/1 W:\domains\localhost\fresh\f1\app\Controllers\importExportController.php(139): FreshRSS_importExport_Controller->importJson()
>     https://github.com/FreshRSS/FreshRSS/issues/2 W:\domains\localhost\fresh\f1\cli\import-for-user.php(31): FreshRSS_importExport_Controller->importFile()
>     https://github.com/FreshRSS/FreshRSS/issues/3 {main}
>     thrown in W:\domains\localhost\fresh\f1\lib\lib_rss.php on line 334`

FreshRSS edge dev vesrion
PHP 8.0

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/5622

* Fix import of article with empty content. Cherry picks on https://github.com/FreshRSS/FreshRSS/pull/5584
* Fix export of tags confused with labels. Regression from https://github.com/FreshRSS/FreshRSS/pull/4490
* Fix bug in some cases when exporting more than 998 labels

### CODE REVIEW

File: app/Controllers/importExportController.php [hunk 1]
```diff
@@ -309,7 +309,7 @@ private function importJson(string $article_file, bool $starred = false): bool {
 		$limits = FreshRSS_Context::$system_conf->limits;
 
 		// First, we check feeds of articles are in DB (and add them if needed).
-		foreach ($items as $item) {
+		foreach ($items as &$item) {
```
Comment (Frenzie) [inline app/Controllers/importExportController.php:312]: What's the specific scenario that can lead to this being necessary?

Comment (Alkarex) [reply app/Controllers/importExportController.php:312]: This is relevant for all the cases when we make changes to `item`, otherwise our changes are not persisted.

```php
<?php

$items = [
	'a' => ['a' => 'b'],
	'b' => ['a' => 'b'],
];

foreach ($items as $item) {
	$item['a'] = 'c';
}

echo json_encode($items);
// Prints: {"a":{"a":"b"},"b":{"a":"b"}}

foreach ($items as &$item) {
	$item['a'] = 'c';
}

echo json_encode($items);
// Prints: {"a":{"a":"c"},"b":{"a":"c"}}
```

Comment (Frenzie) [reply app/Controllers/importExportController.php:312]: I just figured that was generally a negative (within the code here), is all. :-)

**Comment by Alkarex** [comment]
Testing JSON export/import was one of the things I had on my list before releasing 1.22.0 and it turned out there were several issues, which should now hopefully be fixed.
