### PR TITLE
fix: sharing service for mailto links for web mail services

### LINKED ISSUE #2666: Share by email doesnt open in new tab in Firefox
I share a lot of articles by email and really hate the behaviour that sharing an email doesnt open in a new tab in Firefox.

I found this Firefox Bug which is open quite a long time..:
https://bugzilla.mozilla.org/show_bug.cgi?id=646552

I tried to code the suggestion from the last comment in FreshRSS but didnt get a good solution:
https://bugzilla.mozilla.org/show_bug.cgi?id=646552#c28

Maybe there is a workaround (maybe sharing per Email with Firefox ;-) - otherwise we could close this issue and I have to wait until Firefox fixes this behaviour! 

Thank you in advance!

### PR DESCRIPTION
**Pull request by math-GH**
Closes #2666

Firefox does not open the mailto link in a new tab, when a web mailer is set in the browser settings.
https://bugzilla.mozilla.org/show_bug.cgi?id=646552

Add a 2nd email sharing service:

grafik

Changes proposed in this pull request:

- new sharing service
- Javascript: use window.open() for this service

How to test the feature manually:
1. Firefox: set the mailto handler to f.e. Gmail (see: https://support.mozilla.org/en-US/kb/change-program-used-open-email-links)

1. go to configure -> sharing
2. add the new service
3. go to normal view
4. share an article
5. Gmail will opened

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

File: app/i18n/fr/gen.php [hunk 1]
```diff
@@ -194,6 +194,7 @@
 		'clipboard' => 'Presse-papier',
 		'diaspora' => 'Diaspora*',	// IGNORE
 		'email' => 'Courriel',
+		'email-webmail-firefox-fix' => 'Email (webmail - fix for Firefox)',	// TODO
```
Comment (Alkarex) [inline app/i18n/fr/gen.php]:
```suggestion
		'email-webmail-firefox-fix' => 'Courriel (pour Webmail avec Firefox)',
```
