### PR TITLE
Fixed: i18n extensions: 'en' as fallback

### LINKED ISSUE #5419: [BUG] Code tags in extensions options/buttons
**Describe the bug**
In extensions pages, menu or buttons are named after the their code tags.

**To Reproduce**
1) Enable some extension
2) go to its options by clicking on the gear icon

**Expected behavior**
I'd expect to see clear names for menu/options/buttons

**Screenshots**
https://i.imgur.com/alYb34a.jpeg
https://i.imgur.com/Yh0zKR1.jpeg

**Environment information (please complete the following information):**
- Device: Desktop PC
- OS: Windows 10 x64 fully up to date
- Browser: Chrome x64
- FreshRSS version: 1.21.0
- Database version: sqlite3
- PHP version: PHP 7.4
- Installation type: Debian 11, manual install

### PR DESCRIPTION
**Pull request by math-GH**
Closes #5419 and #5425

If users language not provided by the i18n files of the extension then try to fallback to English, if available.

How to test the feature manually:

see #5419

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
I have made a few small changes. Please double-check

**Comment by math-GH** [comment]
> I have made a few small changes. Please double-check

Checked. Works fine. Thanks for your support!

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
Possible regression https://github.com/FreshRSS/FreshRSS/issues/5724#issuecomment-1777011887

File: lib/Minz/Translate.php [hunk 1]
```diff
@@ -125,9 +125,14 @@ public static function registerPath(string $path): void {
 	 */
 	private static function loadLang(string $path): void {
 		$lang_path = $path . '/' . self::$lang_name;
-		if (!file_exists($lang_path) || self::$lang_name == '') {
-			// The lang path does not exist, nothing more to do.
-			return;
+		if (self::$lang_name === '' || !is_dir($lang_path)) {
+			// The lang path does not exist, fallback to English ('en')
+			self::$lang_name = 'en';
```
Comment (Alkarex) [inline lib/Minz/Translate.php:130]: Bug fixed in https://github.com/FreshRSS/FreshRSS/pull/5752
