### PR TITLE
Fix german translation

### LINKED ISSUE #8401: [Bug] German translation for buttons wrong/confusing
### Describe the bug

The German translation for the balloon help of the filter buttons is wrong. It says
**"Nur gelesene anzeigen" ("display only read")
"Nur ungelesene anzeigen" ("display only unread")
"Alle außer Favoriten anzeigen" ("show all except favorites")**

Compare this with the english version:
**'Show read'
'Show unreads'
'Show non-favourites'**

You can see that the meaning is different.

### To Reproduce

1. set freshrss to german
2. hover mouse over icons
3. See error

### FreshRSS version

edge

### PR DESCRIPTION
**Pull request by neuhaus**
Closes #8401

Translation fixes.

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks!
And while you are there, if you feel like it, there are a few TODOs in the same file

**Comment by Frenzie** [comment]
This was changed in <https://github.com/FreshRSS/FreshRSS/pull/1766>. Other translations have the same issue.

**Comment by neuhaus** [comment]
> This was changed in #1766. Other translations have the same issue.

Hey only 7 years later ...

**Comment by Alkarex** [comment]
Thanks! Please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md

**Comment by neuhaus** [comment]
> Thanks! Please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md

pr #8412

File: app/i18n/de/conf.php [hunk 1]
```diff
@@ -107,12 +107,12 @@
 	),
 	'notification_timeout' => array(
 		'bad' => array(
-			'label' => 'Show warning banner',	// TODO
-			'seconds' => 'seconds (at least 1)',	// TODO
+			'label' => 'Zeige Warnbanner',
+			'seconds' => 'Sekundne (mind. 1)',
```
Comment (math-GH) [inline app/i18n/de/conf.php:111]: I am late to the party.

Here is a typo

```suggestion
			'seconds' => 'Sekunden (mind. 1)',
```

File: app/i18n/de/conf.php [hunk 2]
```diff
@@ -107,12 +107,12 @@
...
 		),
 		'good' => array(
-			'label' => 'Show acknowledgement banner',	// TODO
-			'seconds' => 'seconds (0 means not shown)',	// TODO
+			'label' => 'Zeige Anerkennungsbanner',
+			'seconds' => 'Sekunden (0 für nicht gezeigt)',
```
Comment (math-GH) [inline app/i18n/de/conf.php:115]:
```suggestion
			'seconds' => 'Sekunden (0 bedeutet: nicht zeigen)',
```

File: app/i18n/de/conf.php [hunk 3]
```diff
@@ -152,7 +152,7 @@
 			'categories' => 'Nach Kategorie filtern',
 			'feeds' => 'Nach Feed filtern',
 			'order' => 'Nach Datum sortieren',
-			'publish_labels_instead_of_tags' => 'Replace <i>feed tags</i> by <i>user labels</i> in the shared RSS',	// TODO
+			'publish_labels_instead_of_tags' => 'Ersetze <i>feed tags</i> durch <i>user labels</i> im geteilten RSS',
```
Comment (math-GH) [inline app/i18n/de/conf.php:155]: "feed tags" and "user labels" should have a German translation
