### PR TITLE
Fix updated entry filters

### LINKED ISSUE #6331: Apply *mark as read* to updated articles too
### Discussed in https://github.com/FreshRSS/FreshRSS/discussions/6330

<div type='discussions-op-text'>

<sup>Originally posted by **hkcomori** April 18, 2024</sup>
When 'Mark updated articles as unread' triggered, the filter action is not applied.
In my usecase, I set it for articles not wanted to see, so I expect only articles that were not filtered to be unread.

How about your use cases?</div>

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/6331

### CODE REVIEW

File: app/Controllers/feedController.php [hunk 1]
```diff
@@ -587,6 +588,11 @@ public static function actualizeFeeds(?int $feed_id = null, ?string $feed_url =
 								continue;
 							}
 
+							$entry->applyFilterActions($titlesAsRead);
+							if ($readWhenSameTitleInFeed > 0) {
+								$titlesAsRead[$entry->title()] = true;
+							}
+
```
Comment (hkcomori) [inline app/Controllers/feedController.php:595]: `entry_auto_unread` is called before the filter marks articles as read.
I think not calling it for filtered articles because they will be marked as read finally.

Comment (Alkarex) [reply app/Controllers/feedController.php:595]: The action filters are designed to perform more things than just marking as read (although not everything is implemented yet). Already read articles will be skipped a bit later:

https://github.com/FreshRSS/FreshRSS/blob/0ffcf41f9371b9321856d2c709cf7bcb4f7c3c60/app/Models/Entry.php#L661

But let me know if you spot any bug in the logic

Comment (hkcomori) [reply app/Controllers/feedController.php:595]: Oh, not that part.
I think the following part calls `entry_auto_unread` before filter action.

https://github.com/FreshRSS/FreshRSS/blob/094ebf92f7c7fd9af5cb72a27198cffd23cdd4be/app/Controllers/feedController.php#L580-L583

Then apply the filter action:

https://github.com/FreshRSS/FreshRSS/blob/094ebf92f7c7fd9af5cb72a27198cffd23cdd4be/app/Controllers/feedController.php#L591

Articles matching filter action are marked as read finally even though `entry_auto_unread` was called.
But when `entry_auto_unread` was called, I will think articles have been marked as unread (in fact it was marked as read).
So, I think it would be better if `entry_auto_unread` only calls for articles that it finally marks as unread.

Please let me know if my understanding is wrong.

Comment (hkcomori) [reply app/Controllers/feedController.php:595]: Sorry, please forget my comment.

Hook call behavior is a different topic and seems to be consistent with existing policy.
The existing code calls `entry_auto_unread` for no read status change too (unread -> unread).

It seems there is not need to change, because no problems have occurred now.

Comment (Alkarex) [reply app/Controllers/feedController.php:595]: Thanks for commenting again. I had not had time yet to investigate and was about to do so :-)

File: app/Controllers/feedController.php [hunk 2]
```diff
@@ -587,6 +588,11 @@ public static function actualizeFeeds(?int $feed_id = null, ?string $feed_url =
 								continue;
 							}
 
+							$entry->applyFilterActions($titlesAsRead);
```
Comment (Alkarex) [inline app/Controllers/feedController.php:591]: Regression: marking as read for duplicated titles should not apply to updated articles.
Fixed in https://github.com/FreshRSS/FreshRSS/pull/6664

**Comment by Alkarex** [comment]
@hkcomori If you are around, additional tests welcome after https://github.com/FreshRSS/FreshRSS/pull/6664

**Comment by hkcomori** [comment]
@Alkarex Okay, I can't take the time to test specifically, but I'll watch out for any problems while using edge for a while.

**Comment by Alkarex** [comment]
> I'll watch out for any problems while using edge for a while.

Excellent, thanks
