### PR TITLE
Fixes for PHPStan 2.1.42

### LINKED ISSUE #7720: [Bug] Error 403 Forbidden when using Authentik with Nginx
### Describe the bug

I have tried following the guide to setup authentik with freshrss [here](https://integrations.goauthentik.io/integrations/services/freshrss/) but I get a Error 403 - Forbidden when I change the authentication method to HTTP.

I am running freshrss in a docker-compose behind nginx reverse proxy.

Here are the freshrss logs:
```
freshrss    | fde4:1d15:8139:0:5ed4:2b1d:a9c4:154 - - [06/Jul/2025:15:54:37 +0800] "GET /i/?rid=686a28ab5e008 HTTP/1.0" 403 4333 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
freshrss    | [Sun Jul 06 15:54:37.091344 2025] [authz_core:error] [pid 39:tid 39] [client fde4:1d15:8139:0:5ed4:2b1d:a9c4:154:0] AH01630: client denied by server configuration: /var/www/FreshRSS/p/themes/manifest.json
freshrss    | fde4:1d15:8139:0:5ed4:2b1d:a9c4:154 - - [06/Jul/2025:15:54:37 +0800] "GET /themes/manifest.json HTTP/1.0" 403 199 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
```

Here is the docker-compose.yml
```
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - /usr/local/freshrss/data:/var/www/FreshRSS/data
      - /usr/local/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Australia/Perth
      CRON_MIN: '3,33'
    ports:
      - 8080:80
 ```

Here is the .env for the docker-compose:
```
OIDC_ENABLED=1
OIDC_PROVIDER_METADATA_URL=https://sso.tuxtower.net/application/o/freshrss/.well-known/openid-configuration
OIDC_CLIENT_ID=client_id
OIDC_CLIENT_SECRET=client_id_secret
OIDC_X_FORWARDED_HEADERS=X-Forwarded-Port X-Forwarded-Proto X-Forwarded-Host
OIDC_SCOPES=openid email profile
```

Here is the nginx config:
```
server {
	server_name rss.tuxtower.net;

	location / {
		proxy_pass http://10.1.1.85:8080;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-for $proxy_add_x_forwarded_for;
		proxy_set_header X-WebAuth-User    $upstream_http_x_authentik_username;
}



    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/rss.tuxtower.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/rss.tuxtower.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

	# nginx log files
	access_log /var/log/nginx/rss.access.log;
	error_log /var/log/nginx/rss.error.log;

}

server {
    if ($host = rss.tuxtower.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name rss.tuxtower.net;
    return 404; # managed by Certbo

}
```

this is my config.php:
```
<?php
return array (
  'environment' => 'production',
  'salt' => '',
  'base_url' => '',
  'auto_update_url' => 'https://update.freshrss.org',
  'language' => 'en',
  'title' => 'FreshRSS',
  'meta_description' => '',
  'logo_html' => '',
  'default_user' => 'adamw',
  'force_email_validation' => false,
  'allow_anonymous' => false,
  'allow_anonymous_refresh' => false,
  'auth_type' => 'http_auth',
  'http_auth_auto_register' => true,
  'http_auth_auto_register_email_field' => '',
  'api_enabled' => true,
  'unsafe_autologin_enabled' => false,
  'simplepie_syslog_enabled' => true,
  'pubsubhubbub_enabled' => false,
  'allow_robots' => false,
  'allow_referrer' => false,
  'nb_parallel_refresh' => 10,
  'limits' => 
  array (
    'cookie_duration' => 7776000,
    'cache_duration' => 800,
    'cache_duration_min' => 60,
    'cache_duration_max' => 86400,
    'timeout' => 20,
    'max_inactivity' => 9223372036854775807,
    'max_feeds' => 131072,
    'max_categories' => 16384,
    'max_registrations' => 1,
  ),
  'curl_options' => 
  array (
  ),
  'db' => 
  array (
    'type' => 'sqlite',
    'host' => '',
    'user' => '',
    'password' => '',
    'base' => '',
    'prefix' => '',
    'connection_uri_params' => '',
    'pdo_options' => 
    array (
    ),
  ),
  'mailer' => 'mail',
  'smtp' => 
  array (
    'hostname' => '',
    'host' => 'localhost',
    'port' => 25,
    'auth' => false,
    'auth_type' => '',
    'username' => '',
    'password' => '',
    'secure' => '',
    'from' => 'root@localhost',
  ),
  'extensions_enabled' => 
  array (
  ),
  'extensions' => 
  array (
  ),
  'disable_update' => true,
  'trusted_sources' => 
  array (
    0 => '127.0.0.0/8',
    1 => '::1/128',
    2 => '10.1.1.85/32',
    3 => '172.100.0.0/8',
  ),
);
```

### To Reproduce

1. Have Freshrss running in docker-compose behind nginx reverse proxy
2. Follow this guide https://integrations.goauthentik.io/integrations/services/freshrss/
3. Get to the last step of changing the authentication method
4. Get error

### Expected behavior

_No response_

### FreshRSS version

1.26.3

### System information

- Database version: sqlite 3.40.1
- PHP version: PHP 8.2.28
- Installation type: Docker-compose
- Web server type: Nginx

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alkarex**

### CODE REVIEW

File: app/Utils/httpUtil.php [hunk 1]
```diff
@@ -496,9 +496,10 @@ public static function checkTrustedIP(): bool {
 	}
 
 	public static function httpAuthUser(bool $onlyTrusted = true): string {
-		$auths = array_unique(
-			array_intersect_key($_SERVER, ['REMOTE_USER' => '', 'REDIRECT_REMOTE_USER' => '', 'HTTP_REMOTE_USER' => '', 'HTTP_X_WEBAUTH_USER' => ''])
-		);
+		$auths = array_unique(array_filter(
+			array_intersect_key($_SERVER, ['REMOTE_USER' => '', 'REDIRECT_REMOTE_USER' => '', 'HTTP_REMOTE_USER' => '', 'HTTP_X_WEBAUTH_USER' => '']),
+			fn($value) => is_string($value) && $value !== ''
```
Comment (Alkarex) [inline app/Utils/httpUtil.php:501]: Happens to fix https://github.com/FreshRSS/FreshRSS/issues/7720#issuecomment-4063956651 at the same time
