### PR TITLE
Fixes for no-cache.txt

### LINKED ISSUE #7885: [Bug] no-cache.txt causes undefined function errors
### Describe the bug

Create `data/no-cache.txt`

Observe following response in requests like `/i/?c=extension&a=serve&x=User CSS&f=style.css`:

<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function httpConditional() in /var/www/FreshRSS/app/Controllers/extensionController.php:333
Stack trace:
#0 /var/www/FreshRSS/lib/Minz/Dispatcher.php(117): FreshRSS_extension_Controller-&gt;serveAction()
#1 /var/www/FreshRSS/lib/Minz/Dispatcher.php(48): Minz_Dispatcher-&gt;launchAction()
#2 /var/www/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher-&gt;run()
#3 /var/www/FreshRSS/p/i/index.php(59): Minz_FrontController-&gt;run()
#4 {main}
  thrown in <b>/var/www/FreshRSS/app/Controllers/extensionController.php</b> on line <b>333</b><br />

### FreshRSS version

1.27.1-dev

### PR DESCRIPTION
**Pull request by Inverle**
* Closes and fixes error from #7885
* `no-cache.txt` is now respected in `f.php`, `ext.php` and `serve` action in `extensionController`

### CODE REVIEW

File: lib/http-conditional.php [hunk 1]
```diff
@@ -80,7 +80,7 @@
  * @return bool True if the connection can be closed (e.g.: the client has already the latest version), false if the new content has to be send to the client.
  */
 function httpConditional(int $UnixTimeStamp, int $cacheSeconds = 0, int $cachePrivacy = 0, bool $feedMode = false, bool $compression = false, bool $session = false): bool {
-	if (headers_sent()) return false;
+	if (headers_sent() || (defined('NO_CACHE') && constant('NO_CACHE') === true)) return false;
```
Comment (Alkarex) [inline lib/http-conditional.php]: I would rather like to avoid modifying this file if possible, which is meant to be a standalone one.
I would prefer keeping the `if (!file_exists(DATA_PATH . '/no-cache.txt'))` test (also to make it easier to understand, in my opinion).

**Comment by Alkarex** [comment]
Isn't the fix to simply include `require(LIB_PATH . '/http-conditional.php');` unconditionally?

**Comment by Inverle** [comment]
> Isn't the fix to simply include `require(LIB_PATH . '/http-conditional.php');` unconditionally?

I think we don't want to call `httpConditional()` if `no-cache.txt` exists
I didn't want to put `file_exists` in each condition, but I can do that instead if we have to avoid making changes to http-conditional
(since that can also be forgotten later for such a niche feature)

**Comment by Alkarex** [comment]
Yes please 👍🏻

**Comment by Inverle** [comment]
@Alkarex done

File: p/f.php [hunk 2]
```diff
@@ -8,9 +8,12 @@
 header("Content-Security-Policy: default-src 'none'; frame-ancestors 'none'; sandbox");
 header('X-Content-Type-Options: nosniff');
 
+$no_cache = file_exists(DATA_PATH . '/no-cache.txt');
+
 function show_default_favicon(int $cacheSeconds = 3600): void {
+	global $no_cache;
 	$default_mtime = @filemtime(DEFAULT_FAVICON) ?: 0;
-	if (!httpConditional($default_mtime, $cacheSeconds, 2)) {
+	if ($no_cache || httpConditional($default_mtime, $cacheSeconds, 2)) {
```
Comment (Alkarex) [inline p/f.php]: Isn't a `!` missing there?

Comment (Inverle) [reply p/f.php]: Fixed

File: p/f.php [hunk 3]
```diff
@@ -59,11 +62,11 @@ function show_default_favicon(int $cacheSeconds = 3600): void {
 	}
 }
 
-if (!httpConditional($ico_mtime, mt_rand(14, 21) * 86400, 2)) {
+if ($no_cache || httpConditional($ico_mtime, mt_rand(14, 21) * 86400, 2)) {
```
Comment (Alkarex) [inline p/f.php]: And here as well with `!`, right?

**Review by Alkarex — APPROVED** [review]
