### PR TITLE
Shortcuts: auto-load at least a few articles

### LINKED ISSUE #3974: [BUG] Jumping to next article with shortcuts does not load more articles at the bottom
**Describe the bug**
When jumping to the next post/article using a keyboard shortcut works only until "the end of the page" is reached, new articles are not loaded even when there are ones in queue. Pressing the keyboard shortcut in this state, FreshRSS jumps to the next feed, leaving unread articles in the previous one.

In the setttings I have enabled the option: "Load more articles at the bottom of the page"

**To Reproduce**
1. Have a feed with about 80 posts // with a lot of content. (I am using CSS selectors to load content of the article)
2. Press keyboard shortcut for "Open the next (unread) article"
3. Press keyboard shortcut several times, watch the scoll bar, it will scroll down until the bottom of the page.
4. When at the end of the scroll bar pressing the keyboard shortcut again will switch to the next feed. There are still about 30 unread articles in the feed menu, but no content is loaded at the bottom of the page.

If there are no additional feeds, the view will simply stop, and won't switch anywhere though there are additonal articles available. Simply by using the mouse wheel to scroll up a little bit, then scroll down a bit, suddenly loads additional articles at the bottom of the page.

**Expected behavior**
There should be content loaded at the bottom of the page when using the keyboard shortcut to scroll down.

**Screenshots**
Not applicable

**Environment information (please complete the following information):**
- Device: PC
- OS: Windows 10
- Browser: Chrome 95
- FreshRSS version: 1.19.0-dev
- Database version: not relevant
- PHP version: not relevant]
- Installation type: selfhosted? shared hoster?

**Additional context**
No context

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/3974

### CODE REVIEW

File: p/scripts/main.js [hunk 1]
```diff
@@ -720,11 +720,24 @@ function onScroll() {
...
+				for (let i = 5; i > 0; i--) {
+					sibling = sibling.nextElementSibling;
+					if (!sibling) {
+						// Too few pre-loaded articles
+						load_more_posts();
+						break;
+					}
+				}
+			}
 		}
```
Comment (aledeg) [inline p/scripts/main.js]: I like what you did here.
I think you can simplify that with:
```javascript
} else if (document.querySelectorAll('.flux.current ~ .flux').length <= 5) {
    load_more_posts();
}
```

I cannot find a feed to reproduce on my dev instance. I'll get back to you when I find one.

Comment (aledeg) [reply p/scripts/main.js]: I could reproduce the bug with the current branch using this feed (https://hackaday.com/blog/feed/). Your solution fixes the bug. Mine too.

On another topic, I think we should add some marker on the last article to alert the user that it will switch feed after the current article.

Comment (aledeg) [reply p/scripts/main.js]: FYI https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_combinator

**Comment by aledeg** [comment]
@Alkarex I've seen that you've changed the milestone for that PR. I am so sad!

But there is some inconsistency since the linked bug is in a different milestone.

**Comment by Alkarex** [comment]
> @Alkarex I've seen that you've changed the milestone for that PR. I am so sad!

This is because I was afraid of risks of regressions. But if you feel like testing a bit more with different settings, we could try to push it :-)

**Comment by aledeg** [comment]
What kind of settings do you have in mind? I've tested it with the aforementioned feed and it was working fine.

I've also seen that you didn't include my code suggestion. Did you find something bothering you on it?

**Comment by Alkarex** [comment]
> What kind of settings do you have in mind? I've tested it with the aforementioned feed and it was working fine.

Articles collapsed, expended, with auto-load or not, auto-mark-as-read or not, small screen, large screen...
I have been running with it since this PR and I have not observed any issue.

> I've also seen that you didn't include my code suggestion. Did you find something bothering you on it?

I did include your suggestion (General sibling combinator), didn't I?

**Comment by aledeg** [comment]
I will make some tests later today. I'll let you know.

**Comment by aledeg** [comment]
My bad. I didn't check the edge branch but the content of the PR. Must have been stuck in my browser cache. Forget my comment :)

**Comment by aledeg** [comment]
I've performed the following tests with success:
- [x] articles collapsed with auto-load not auto-mark as read large screen.
- [x] articles collapsed with auto-load not auto-mark as read small screen.
- [x] articles expanded with auto-load not auto-mark as read large screen.
- [x] articles expanded with auto-load not auto-mark as read small screen.
- [x] articles collapsed without auto-load not auto-mark as read large screen.
- [x] articles collapsed without auto-load not auto-mark as read small screen.
- [x] articles expanded without auto-load not auto-mark as read large screen.
- [x] articles expanded without auto-load not auto-mark as read small screen.
- [x] articles collapsed with auto-load auto-mark as read large screen.
- [x] articles collapsed with auto-load auto-mark as read small screen.
- [x] articles expanded with auto-load auto-mark as read large screen.
- [x] articles expanded with auto-load auto-mark as read small screen.
- [x] articles collapsed without auto-load auto-mark as read large screen.
- [x] articles collapsed without auto-load auto-mark as read small screen.
- [x] articles expanded without auto-load auto-mark as read large screen.
- [x] articles expanded without auto-load auto-mark as read small screen.

**Comment by Alkarex** [comment]
Looks good 👍🏻

**Comment by math-GH** [comment]
Hey @Alkarex , could you please check here: I would say that the article loading is triggered to often. When I scroll down 10pixels, than the next article fetch is triggered. Next 10pixels again. (see also the scroll bar that indicates a very long article list)

**Comment by Alkarex** [comment]
@math-GH Could you tell a bit with with settings / window size, etc. you can produce the problem?

**Comment by math-GH** [comment]
I scrolled just twice about 10 pixels. You can see that the scroll bar becomes smaller and smaller and it fires Ajax requests.
scroll

No special settings in the config
grafik

**Comment by Alkarex** [comment]
Ah, I believe there is a bug with the CSS selector when there is no article selected

**Comment by Alkarex** [comment]
Please check https://github.com/FreshRSS/FreshRSS/pull/4593

**Comment by math-GH** [comment]
> Please check #4593

checked. It fix the issue. Nice night work ;)
