### PR TITLE
OPML export/import of some proprietary FreshRSS attributes

### LINKED ISSUE #4077: [BUG] Advanced option like "Filter actions" are not saved using the export option to fully migrate a configuration
**Describe the bug**
"Filter actions" are not saved using the export option to migrate a configuration

**To Reproduce**
1. Go to subscription management and add something to "Filter actions" on one feed subscription, then save
Filter_Actions
2. Go to "Import / Export" and export all your conf (here are extract with only the parts about that feed)
[feed_2021-12-22_8_114.json.txt](https://github.com/FreshRSS/FreshRSS/files/7761534/feed_2021-12-22_8_114.json.txt)
[feeds_2021-12-22.opml.xml.txt](https://github.com/FreshRSS/FreshRSS/files/7761608/feeds_2021-12-21.opml.xml.txt)
3. Restore that conf on another FreshRSS install with the "Import" option
4. See that the "Filter actions" stays empty (the info doesn't even seem to be in the exported opml.xml file)

**Expected behavior**
Exporting all the configuration of the feed subscriptions (so also all fields modified, not only "Filter actions" if there are others) 

**Environment information (please complete the following information):**
Export done on FreshRSS 1.19.0-dev (git) in a LXC container running debian OS with postgreSQL DB, import in FreshRSS official Docker alpine tag sqlite DB

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/4077
And one of the TODOs of https://github.com/FreshRSS/FreshRSS/pull/4220
So far: XPath options, CSS Selector, and action filters:

```xml
<outline xmlns:frss="https://freshrss.org/#v1"
  text="Example"
  type="HTML+XPath"
  xmlUrl="https://www.example.net/page.html"
  htmlUrl="https://www.example.net/page.html"
  description="Example of Web scraping"
  frss:xPathItem="//a[contains(@href, '/interesting/')]/ancestor::article"
  frss:xPathItemTitle="descendant::h2"
  frss:xPathItemContent="."
  frss:xPathItemUri="descendant::a[string-length(@href)&gt;0]/@href"
  frss:xPathItemThumbnail="descendant::img/@src"
  frss:cssFullContent="article"
  frss:filtersActionRead="intitle:⚡️ OR intitle:🔥&#10;something"
/>
```

I do not believe we should export everything in OPML, but those attributes at least make sense.

Relevant parts of the [OPML specification](http://opml.org/spec2.opml):

> An OPML file may contain elements and attributes not described on this page, only if those elements are defined in a namespace

> OPML can also be extended by the addition of new values for the type attribute

_Notes_: Modifies the `lib_opml` library to support (basic) XML namespaces. Like previous PRs such as https://github.com/FreshRSS/FreshRSS/pull/1112 , https://github.com/FreshRSS/FreshRSS/pull/1206 , but the [library has been archived](https://github.com/marienfressinaud/lib_opml/) so my upstream issues / PRs are not visible anymore.  The author of `lib_opml` ( @marienfressinaud ) wrote:

> After (too) many years, I'm going to clean the lib_opml code and "end" it (there's nothing to add until the spec changes)

### CODE REVIEW

File: app/Services/ExportService.php [hunk 1]
```diff
@@ -19,6 +19,10 @@ class FreshRSS_Export_Service {
 	/** @var FreshRSS_TagDAO */
 	private $tag_dao;
 
+	const FRSS_NAMESPACE = 'https://freshrss.org/#v1';
```
Comment (Alkarex) [inline app/Services/ExportService.php]: @marienfressinaud Any comment? :-)
(I would suggest a redirect to a documentation page)
Alternatives include http://purl.org , maybe http://xmlns.com / http://opml.org (more ambitious), or a non-URL URI

**Comment by marienfressinaud** [comment]
To be clearer, I continue the work at https://framagit.org/marienfressinaud/lib_opml and I'm currently improving the support for special attributes (cf. https://framagit.org/marienfressinaud/lib_opml/-/merge_requests/16). Since it's not finished yet, I still can add the support for custom namespaces :)

File: app/Services/ExportService.php (hunk 1 above)
Comment (marienfressinaud) [reply app/Services/ExportService.php]: https://freshrss.org/opml ? (I will not be able to redirect the `#v1` hash)

Comment (Alkarex) [reply app/Services/ExportService.php]: https://freshrss.org/opml looks good @marienfressinaud :-)
(Of course for `#v1` but it was to avoid introducing a non-working URL so far)

Comment (marienfressinaud) [reply app/Services/ExportService.php]: Ok, let me know when the documentation page is ready, I'll do the redirection then

Comment (Alkarex) [reply app/Services/ExportService.php]: https://github.com/FreshRSS/FreshRSS/pull/4342/commits/54cb9388c6e60145236f7ba9799b1d3881bab58e

Comment (Alkarex) [reply app/Services/ExportService.php]: @marienfressinaud Here you are https://freshrss.github.io/FreshRSS/en/developers/OPML.html

Comment (marienfressinaud) [reply app/Services/ExportService.php]: Done! https://freshrss.org/opml (code 302 for now)

Comment (Alkarex) [reply app/Services/ExportService.php]: Super 👍🏻
