### PR TITLE
FeverAPI fix enclosures

### LINKED ISSUE #5209: [BUG] Images in enclosure in the Fever API
**Describe the bug**
The `html` field of articles in the Fever API had image enclosure attached to the article content, for feeds that had images as enclosures, but not in the content.

This is no longer the case for articles fetched after upgrading to 1.21.0, when syncing with the Fever API, but still works when syncing with the Google Reader API.

**To Reproduce**
- Refresh the feed on 1.21.0
- Sync with Fever API

**Expected behavior**
The article content should be the same in the FreshRSS and Google Reader APIs.

**Environment information (please complete the following information):**
- Example feed: https://www.digi24.ro/rss
- FreshRSS version: 1.21.0

**Additional context**
Fiery Feeds dev here - I'm going to switch to the Google Reader API soonish, if that is relevant for prioritisation :)

### PR DESCRIPTION
**Pull request by Alkarex**
Fix regression: provide enclosures as part of HTML content body in FeverAPI
#fix https://github.com/FreshRSS/FreshRSS/issues/5209

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Looks simple, but I don't have Fever things at hand to check.

**Comment by Alkarex** [comment]
Can be tested with cURL:

```sh
api_key=`echo -n "alice:secretPassword" | md5sum | cut -d' ' -f1`
curl -s -F "api_key=$api_key" 'https://freshrss.example.net/api/fever.php?api&items&with_ids=1679231293688643' | jq .
```

File: app/Models/Entry.php [hunk 1]
```diff
@@ -187,6 +187,7 @@ public function content(bool $withEnclosures = true, bool $allowDuplicateEnclosu
 			$thumbnails = $enclosure['thumbnails'] ?? [];
 			$etitle = $enclosure['title'] ?? '';
 
+			$content .= "\n";
```
Comment (math-GH) [inline app/Models/Entry.php:190]: @Alkarex  How is it important for the Fever API?

Comment (Alkarex) [reply app/Models/Entry.php:190]: Not much, but we are concatenating a `<figure ...>...` HTML code right after, and that made the output code difficult to read. Furthermore, I cannot remember for sure, but I believe that having no white-space at all can sometimes lead to a different rendering for some styling rules.
