### PR TITLE
OIDC_SCOPES compatibility colon

### LINKED ISSUE #5744: [BUG] OIDC: Variable name must not contain ':'
Variable being passed:

```
OIDC_SCOPES: "user:email"
```

Why this is a bug?

Because scopes are allowed to contain colons. 

See https://goauthentik.io/docs/providers/oauth2/

![image](https://github.com/FreshRSS/FreshRSS/assets/5262735/0d332195-2095-4449-ac6b-e1ca6f37bb3d)


Logs:

```
│ stream logs failed container "freshrss" in pod "freshrss-0" is waiting to start: ContainerCreating for freshrss/freshrss-0 (freshrss)                                                                                                                 │
│ stream logs failed container "freshrss" in pod "freshrss-0" is waiting to start: ContainerCreating for freshrss/freshrss-0 (freshrss)                                                                                                                 │
│ stream logs failed container "freshrss" in pod "freshrss-0" is waiting to start: ContainerCreating for freshrss/freshrss-0 (freshrss)                                                                                                                 │
│ Enabling module auth_openidc.                                                                                                                                                                                                                         │
│ apache2: Syntax error on line 225 of /etc/apache2/apache2.conf: Syntax error on line 44 of /etc/apache2/sites-enabled/FreshRSS.Apache.conf: Variable name must not contain ':'                                                                        │
│ Stream closed EOF for freshrss/freshrss-0 (freshrss)  
```

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/5744

### CODE REVIEW

File: Docker/entrypoint.sh [hunk 1]
```diff
@@ -23,6 +23,11 @@ fi
 
 if [ -n "$OIDC_ENABLED" ] && [ "$OIDC_ENABLED" -ne 0 ]; then
 	a2enmod -q auth_openidc
+	if [ -n "$OIDC_ENABLED" ]; then
```
Comment (Alkarex) [inline Docker/entrypoint.sh:26]: Wrong variable test, fixed in https://github.com/FreshRSS/FreshRSS/pull/5764
