### PR TITLE
fix: repair cli/health.php for OIDC installations

### LINKED ISSUE #8039: [Bug] cli/health.php doesn't work when OIDC enabled
### Describe the bug

Current healthcheck logic doesn't work with OIDC.

Here is the original checks:

```php
if ($httpCode !== 200 || !is_string($content) || !str_contains($content, 'jsonVars') || !str_contains($content, '</html>')) {
```

For OIDC:

1. `httpCode` will be 302 (moved)
2. `content`  doesn't contain "json"

This line will work:

```php
if (($httpCode !== 302 && $httpCode !==200) || !is_string($content) || !str_contains($content, '</html>')) {
```

### To Reproduce

1. Enable OIDC
2. Run `cli/health.php`
3. Get exit code (`echo $?`)

### Expected behavior

Script exit code should be 0

### FreshRSS version

1.27.1

### PR DESCRIPTION
**Pull request by GreyChame1eon**
Connected with #8039
This changes will restore healthcheck process both for classic and OIDC logins

Closes #8039

Changes proposed in this pull request:

- URL changed to "/api"  instead of "/i"
- Content filter changed

How to test the feature manually:

1. replace the original file
2. execute healthcheck: `cli/health.php`
3. vaildate the exit code: `echo $?`. It should be 0 if FreshRSS run successfully

Pull request checklist:

- [X] clear commit messages
- [X] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

File: cli/health.php [hunk 1]
```diff
@@ -26,6 +26,6 @@
 $content = curl_exec($ch);
 $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
 
-if ($httpCode !== 200 || !is_string($content) || !str_contains($content, 'jsonVars') || !str_contains($content, '</html>')) {
+if ($httpCode !== 200 || !is_string($content) || !str_contains($content, 'FreshRSS API endpoints') || !str_contains($content, '</html>')) {
```
Comment (Frenzie) [inline cli/health.php]: That doesn't work. `jsonVars` is a technical detail guaranteed to be present if things are well, while 'FreshRSS API endpoints' is a translated string. Something like `../scripts/api.js` might indicate a somewhat similar point on that page, i.e., that config and translations are guaranteed to be functional.

Comment (Alkarex) [reply cli/health.php]: Done: https://github.com/FreshRSS/FreshRSS/pull/8040/commits/f1365733e719ca9c298e3073e2732622fd4b1a87

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
Thanks @GreyChame1eon . Please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md

Merged. Additional tests and feedback welcome.
