### PR TITLE
Fix login

### LINKED ISSUE #5953: [BUG]Password mismatch on new install
**Describe the bug：**

I'm gonna make this short. Exactly the same behavior as https://github.com/FreshRSS/FreshRSS/issues/5673#issuecomment-1838038920

I'm facing the same exact problem: "Password mismatch".

And i change the nginx config same with [this](https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#hosted-as-domain-root)

Confusingly, the problem existed with **edge tag**, and after I **downgraded to freshrss/freshrss:1.22.1-arm**, the problem disappeared.

Environment information (please complete the following information):

Device: linux
OS: Ubuntu 20.04.3 LTS（aarch64）
Browser: MS Edge Latest
FreshRSS version: [docker edge](https://hub.docker.com/layers/freshrss/freshrss/edge/images/sha256-7c373800504aac348cb4eb8dee06592f0d32cd74713676c1f18a5213e63cd3e7)
Database version: integrated sqlite
PHP version: ?
Installation type: Docker

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/5953
Regression due to https://github.com/FreshRSS/FreshRSS/pull/5946

### CODE REVIEW

File: app/Controllers/userController.php [hunk 1]
```diff
@@ -9,7 +9,7 @@ class FreshRSS_user_Controller extends FreshRSS_ActionController {
 	 * The username is also used as folder name, file name, and part of SQL table name.
 	 * '_' is a reserved internal username.
 	 */
-	public const USERNAME_PATTERN = '([0-9a-zA-Z_][0-9a-zA-Z_.@-]{1,38}|[0-9a-zA-Z])';
+	public const USERNAME_PATTERN = '([0-9a-zA-Z_][0-9a-zA-Z_.@\-]{1,38}|[0-9a-zA-Z])';
```
Comment (Alkarex) [inline app/Controllers/userController.php:12]: There was also a bug in the login with the pattern, which seems to insist on escaping `-` also when it is at the end of the class

Comment (Alkarex) [reply app/Controllers/userController.php:12]: https://github.com/FreshRSS/FreshRSS/pull/7009
