### PR TITLE
Better authorization label for OIDC

### LINKED ISSUE #7254: [Bug] OIDC login auth always logs in admin user
### Describe the bug

I have configured [Authelia IdP for FreshRSS](https://authelia-next.netlify.app/integration/openid-connect/freshrss/) and configured it exactly as defined in the guide (link goes to Authelia's FreshRSS guide). I've also compared it to the [FreshRSS OIDC authentication](https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html) guide. I have one admin user and one test user defined (belonging to IdP groups `admin` and `users` respectively).

Whenever I go to my FreshRSS server it successfully redirects me to Authelia. When I enter my credentials for the "test" user however, it instead logs me in as my Admin user. As an experiment I've tried adding other users and logging in with those but it always authenticates as the Admin user regardless.

### To Reproduce

1. Go to freshrss.<domain>
2. Enter my user credentials
3. Always logs in as my Admin user no matter what credentials are sent by Authelia back to FreshRSS

### Expected behavior

FreshRSS either creates a new user and logs me in or it rejects me because the user is not known to FreshRSS. Preferably the former, but even the latter is better than always logging in as Admin no matter what credentials are used.

### FreshRSS version

1.25.0

### System information

- Database version: SQLite
- PHP version: Unknown
- Installation type: Docker (docker.io/freshrss/freshrss:1.25.0)
 -Web server type: Unknown
- Device: PC
- OS: Win11
- Browser: Firefox

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alkarex**
Reword description of HTTP login method to include OIDC
fix https://github.com/FreshRSS/FreshRSS/issues/7254#issuecomment-2615838151
And remove several duplicated i18n entries.
And add to documentation https://www.authelia.com/integration/openid-connect/freshrss/

image

image

### CODE REVIEW

File: app/i18n/en/admin.php [hunk 1]
```diff
@@ -16,7 +16,7 @@
 		'allow_anonymous_refresh' => 'Allow anonymous refresh of the articles',
 		'api_enabled' => 'Allow <abbr>API</abbr> access <small>(required for mobile apps and sharing user queries)</small>',
 		'form' => 'Web form (traditional, requires JavaScript)',
-		'http' => 'HTTP (for advanced users with HTTPS)',
+		'http' => 'HTTP (advanced: managed by Web server, OIDC, SSO…)',
```
Comment (Frenzie) [inline app/i18n/en/admin.php:19]: The AP stylebook and a few others no longer recommend capitalizing web fwiw. (I prefer lowercase, but that might just be my non-English bias. They like capitalizing things a lot more than we do.)

**Review by Frenzie — APPROVED** [review]
Ignore the comment. Or don't. ;-)

File: app/i18n/en/admin.php (hunk 1 above)
Comment (Alkarex) [reply app/i18n/en/admin.php:19]: I did not know. I am still old school on that, apparently :-) For me *Web* is more precise than *web* (as in spider web):
* https://en.wiktionary.org/wiki/web
* https://en.wiktionary.org/wiki/Web

And this is what we have everywhere else in the current code base.
Do you use an upper case in *the Web* but not in *Web server*? Or in none of them?

Comment (Frenzie) [reply app/i18n/en/admin.php:19]: None. Which most style guides have also switched to about a decade ago. But if the FreshRSS style guide says Web let it be Web. :-)

File: app/i18n/it/admin.php [hunk 2]
```diff
@@ -16,7 +16,7 @@
 		'allow_anonymous_refresh' => 'Consenti agli utenti anonimi di aggiornare gli articoli',
 		'api_enabled' => 'Consentire l’accesso all’<abbr>API</abbr> <small>(necessario per le app e per la condivisione delle query degli utenti)</small>',
 		'form' => 'Web form (tradizionale, richiede JavaScript)',
-		'http' => 'HTTP (per gli utenti avanzati con HTTPS)',
+		'http' => 'HTTP (advanced: managed by Web server, OIDC, SSO…)',	// TODO
```
Comment (UserRoot-Luca) [inline app/i18n/it/admin.php]:
```suggestion
		'http' => 'HTTP (avanzato: gestito da server Web, OIDC, SSO…)',
```

File: app/i18n/nl/admin.php [hunk 3]
```diff
@@ -16,7 +16,7 @@
 		'allow_anonymous_refresh' => 'Sta bezoekers toe om de artikelen te vernieuwen',
 		'api_enabled' => 'Sta <abbr>API</abbr> toegang toe <small>(nodig voor mobiele apps and sharing user queries)</small>',	// DIRTY
 		'form' => 'Web formulier (traditioneel, JavaScript vereist)',
-		'http' => 'HTTP (voor gevorderde gebruikers met HTTPS)',
+		'http' => 'HTTP (advanced: managed by Web server, OIDC, SSO…)',	// TODO
```
Comment (Frenzie) [inline app/i18n/nl/admin.php]:
```suggestion
		'http' => 'HTTP (geavanceerd: beheerd door webserver, OIDC, SSO…)',
```

File: app/i18n/en/admin.php (hunk 1 above)
Comment (Alkarex) [reply app/i18n/en/admin.php:19]: > if the FreshRSS style guide says

Haha, I do think we have such a thing yet, but let's come back to it another time if it bothers anyone
