### PR TITLE
Fix login

### LINKED ISSUE #5270: The authentication form does not appear
Hello,

I have recently installed FreshRSS on my server, but I am experiencing an issue where the login form is not displaying. Instead, I am receiving a PHP Fatal error in the log file, which mentions the Minz_Url::serialize() function and a null value being passed as an argument where an array is expected.

- Raspberry Pi
- Debian GNU/Linux 11 (bullseye)
- Firefox 102.9
- mysql  Ver 15.1
- PHP 8.1.17

Could you please advise on how to resolve this issue?

Thank you for your help.

`[Fri Apr 07 15:13:01.652035 2023] [php:error] [pid 791] [client 192.168.1.1:35952] PHP Fatal error:  Uncaught TypeError: Minz_Url::serialize(): Argument #1 ($url) must be of type array, null given, called in /var/www/freshrss/app/views/auth/formLogin.phtml on line 13 and defined in /var/www/freshrss/lib/Minz/Url.php:131\nStack trace:\n#0 /var/www/freshrss/app/views/auth/formLogin.phtml(13): Minz_Url::serialize()\n#1 /var/www/freshrss/lib/Minz/View.php(94): include('...')\n#2 /var/www/freshrss/lib/Minz/View.php(116): Minz_View->includeFile()\n#3 /var/www/freshrss/app/layout/layout.phtml(70): Minz_View->render()\n#4 /var/www/freshrss/lib/Minz/View.php(94): include('...')\n#5 /var/www/freshrss/lib/Minz/View.php(107): Minz_View->includeFile()\n#6 /var/www/freshrss/lib/Minz/View.php(74): Minz_View->buildLayout()\n#7 /var/www/freshrss/lib/Minz/Dispatcher.php(56): Minz_View->build()\n#8 /var/www/freshrss/lib/Minz/FrontController.php(60): Minz_Dispatcher->run()\n#9 /var/www/freshrss/p/i/index.php(57): Minz_FrontController->run()\n#10 {main}\n  thrown in /var/www/freshrss/lib/Minz/Url.php on line 131
`

### PR DESCRIPTION
**Pull request by Alkarex**
Fix https://github.com/FreshRSS/FreshRSS/issues/5270

### CODE REVIEW

File: lib/Minz/Request.php [hunk 1]
```diff
@@ -374,12 +374,12 @@ public static function getNotification(): ?array {
...
 	 * Relance une requête
-	 * @param array{'c'?:string,'a'?:string,'params'?:array<string,mixed>} $url l'url vers laquelle est relancée la requête
+	 * @param string|array{'c'?:string,'a'?:string,'params'?:array<string,mixed>} $url l'url vers laquelle est relancée la requête
 	 * @param bool $redirect si vrai, force la redirection http
 	 *                > sinon, le dispatcher recharge en interne
 	 */
-	public static function forward(array $url = [], bool $redirect = false): void {
-		if (empty(Minz_Request::originalRequest()) && strpos('auth', json_encode($url)) !== false) {
+	public static function forward($url = [], bool $redirect = false): void {
+		if (empty(Minz_Request::originalRequest())) {
```
Comment (Alkarex) [inline lib/Minz/Request.php:382]: Slight change of logic from https://github.com/FreshRSS/FreshRSS/pull/4654
