### PR TITLE
Fix error handling when updating URL

### LINKED ISSUE #4813: Error messages could be better in case of an unreachable database
I had a problem which lead to my database being down.

Symptoms were quite far off the expected ones:
- red flag "A request has failed, it may have been caused by internet connection problems." on top of the opened webpage
- HTTP ERROR 500 when reloading the webpage
- at the same time, no log in /data/users/_/*
- at the same time, logs in Apache2:
```
[Fri Nov 04 14:27:08.282930 2022] [proxy_fcgi:error] [pid 44370:tid 139728266151488] [client x.x.x.x:11919] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key 1 in /var/www/html/freshrss/lib/lib_rss.php on line 821'
[Fri Nov 04 14:27:08.283032 2022] [proxy_fcgi:error] [pid 44370:tid 139728266151488] [client x.x.x.x:11919] malformed header from script 'index.php': Bad header: \t</body></html>
[Fri Nov 04 14:27:08.283106 2022] [proxy_fcgi:error] [pid 44370:tid 139728266151488] [client x.x.x.x:11919] AH01070: Error parsing script headers
[Fri Nov 04 14:27:08.283122 2022] [proxy_fcgi:error] [pid 44370:tid 139728266151488] (22)Invalid argument: [client x.x.x.x:11919] AH01075: Error dispatching request to :
[Fri Nov 04 14:28:01.653278 2022] [proxy_fcgi:error] [pid 44370:tid 139728266151488] [client x.x.x.x:12224] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key 1 in /var/www/html/freshrss/lib/lib_rss.php on line 821'
[Fri Nov 04 14:28:01.653382 2022] [proxy_fcgi:error] [pid 44370:tid 139728266151488] [client x.x.x.x:12224] malformed header from script 'index.php': Bad header: \t</body></html>
[Fri Nov 04 14:28:01.653478 2022] [proxy_fcgi:error] [pid 44370:tid 139728266151488] [client x.x.x.x:12224] AH01070: Error parsing script headers
[Fri Nov 04 14:28:01.653636 2022] [proxy_fcgi:error] [pid 44370:tid 139728266151488] (22)Invalid argument: [client x.x.x.x:12224] AH01075: Error dispatching request to :
```

None of these helped me to understand that the database was down.

**To Reproduce**
Steps to reproduce the behavior: just stop mysql/mariadb/postgresql db engine.

**Expected behavior**
Message indicating that the database is not reachable.

### PR DESCRIPTION
**Pull request by Alkarex**
Fix 3 related errors handling when updating the feed URL with an invalid URL. Previously leading to unclear 500 page with additional PHP errors.

### CODE REVIEW

File: app/Controllers/subscriptionController.php [hunk 1]
```diff
@@ -256,7 +256,7 @@ public function feedAction() {
 					$url_redirect = array('c' => 'subscription', 'params' => array('id' => $id));
 			}
 
-			if ($feedDAO->updateFeed($id, $values) !== false) {
+			if ($values['url'] != '' && $feedDAO->updateFeed($id, $values) !== false) {
```
Comment (Alkarex) [inline app/Controllers/subscriptionController.php:259]: The URL is blank here if it was detected to be invalid just before

File: app/Models/Feed.php [hunk 2]
```diff
@@ -259,13 +259,14 @@ public function _id($value) {
...
 	public function _url(string $value, bool $validate = true) {
 		$this->hash = '';
+		$url = $value;
 		if ($validate) {
-			$value = checkUrl($value);
+			$url = checkUrl($url);
 		}
-		if ($value == '') {
+		if ($url == '') {
 			throw new FreshRSS_BadUrl_Exception($value);
```
Comment (Alkarex) [inline app/Models/Feed.php:267]: The original URL was lost for the exception message

File: lib/lib_rss.php [hunk 3]
```diff
@@ -845,7 +845,7 @@ function errorMessageInfo($errorTitle, $error = '') {
 	$details = '';
 	// Prevent empty tags by checking if error isn not empty first
 	if ($error) {
-		$error = htmlspecialchars($error, ENT_NOQUOTES, 'UTF-8');
+		$error = htmlspecialchars($error, ENT_NOQUOTES, 'UTF-8') . "\n";
```
Comment (Alkarex) [inline lib/lib_rss.php:848]: The `list()` syntax below assumes at least two lines, which is not always the case.
