### PR TITLE
Fix feeds encoded in UTF-16LE

### LINKED ISSUE #7690: [Bug] Unable to subscribe to HIBP breaches feed – “invalid XML, mismatched tag” error
### To Reproduce

1. Open **Subscriptions → +Add**  
2. Enter `https://haveibeenpwned.com/feed/breaches/`  
3. Leave all options at their default and click *Add**

### Expected behavior

The feed is accepted and the articles are fetched, as happens in Thunderbird, Feedbin and other readers.

### FreshRSS version

1.26.3

### System information

- Database version: pdo_mysql
- PHP version: 8.2.28
- Installation type: GitHub Source
- Web server type: Apache
- Device: Computer
- OS: Debian
- Browser: Firefox

### Current behaviour
FreshRSS shows the error below and refuses to add the feed:

```
https://haveibeenpwned.com/feed/breaches/ is invalid XML, likely due to invalid characters.
XML error: Mismatched tag at line 75, column 509 [https://haveibeenpwned.com/feed/breaches/]
```

### Feed excerpt around the failing line
```xml
...                                                      
<title>TehetségKapu - 54,357 breached accounts</title>  <!-- line 75 -->
...
<title>Fédération Francaise de Rugby - 281,977 breached accounts</title> <!-- line 59 -->
```

The second title also contains accented characters and does not trigger an error.

### Request

Could you please advise how to debug this further, or confirm whether FreshRSS’ parser needs to be adjusted for this feed? Or should I report any errors to HiBP?

Thanks for your help!

### PR DESCRIPTION
**Pull request by Alkarex**
Fix https://github.com/FreshRSS/FreshRSS/issues/7690
https://github.com/FreshRSS/simplepie/pull/40
The final character `>` of a feed is encoded as `3E 00` in UTF-16LE, so calling `trim()` was removing the `\x00`, breaking the multibyte encoding and making the feed invalid.

Upstream PR https://github.com/simplepie/simplepie/pull/916

### CODE REVIEW

File: lib/simplepie/simplepie/src/File.php [hunk 1]
```diff
@@ -162,7 +162,7 @@ public function __construct(string $url, int $timeout = 10, int $redirects = 5,
                     $parser = new \SimplePie\HTTP\Parser($responseHeaders, true);
                     if ($parser->parse()) {
                         $this->set_headers($parser->headers);
-                        $this->body = trim($parser->body);
+                        $this->body = trim($parser->body, " \n\r\t\v"); // Do not trim \x00 to avoid breaking BOM or multibyte characters
```
Comment (Frenzie) [inline lib/simplepie/simplepie/src/File.php]: Sneaky. :-)

**Review by Frenzie — APPROVED** [review]

**Comment by Alkarex** [comment]
Update to cover more paths https://github.com/simplepie/simplepie/pull/917
