### PR TITLE
fix broken sharing services

### LINKED ISSUE #3793: [BUG] Sharing/Integration: broken "more information" links
Configuration: Sharing
grafik

"more information" button:

- Blogotext: link (https://lehollandaisvolant.net/blogotext/fr/) is broken/useless. Leads to a 404 page. I guess this sharing we could delete. The last release was in 2017 (see https://github.com/BlogoText/blogotext )
- Lemmy: link leads to the sharing paged itself. The link is useless. Is it this Lemmy https://github.com/LemmyNet/lemmy ?
- Movim: link leads to github page. A better link could be https://movim.eu/

**Environment information (please complete the following information):**
 - FreshRSS version: 1.18.1

### PR DESCRIPTION
**Pull request by math-GH**
Closes #3793 

Changes proposed in this pull request:

- Blogotext: deleted
- Lemmy: set link
- Movim: changed link
- mastadon: set link
- reordered array

How to test the feature manually:
1. go to integration/share settings
2. edit/add the services
3. check the help buttons

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by aledeg** [comment]
While it seems that blogotext is discontinued, I won't remove it since user might still use it. If it's still working, we should keep it. For the other modifications, I am all-in.

**Comment by math-GH** [comment]
> 
> 
> While it seems that blogotext is discontinued, I won't remove it since user might still use it. If it's still working, we should keep it. For the other modifications, I am all-in.

Blogotex is dead. Last "not dead" message was in 2019: https://github.com/BlogoText/blogotext/issues/384
Last release in 2017.
Let's remove the sharing and wait if someone will open an issue

File: app/shares.php [hunk 1]
```diff
@@ -134,14 +102,14 @@
 		'form' => 'simple',
 		'method' => 'GET',
 	),
-	'lemmy' => array(
-		'url' => '~URL~/create_post?url=~LINK~&name=~TITLE~',
+	'pocket' => array(
+		'url' => 'https://getpocket.com/save?url=~LINK~&amp;title=~TITLE~',
```
Comment (Frenzie) [inline app/shares.php:113]: Is this changing it from set your own server URL to a specific one? Mozilla's working on opening up the server (cf. `https://github.com/Pocket/extension-save-to-pocket/issues/75#issuecomment-655311178`) and there's also https://github.com/open-pocket/open-pocket

It might be worth taking into consideration somehow, but no big deal for now.

Comment (math-GH) [reply app/shares.php:113]: This div does not make sense.
The pocket settings I did not change.
But after all I changed the order of the array, that is why it looks weird

Comment (math-GH) [reply app/shares.php:113]: reordering made with commit e7ca768

Comment (Frenzie) [reply app/shares.php:113]: I see, it says Lemmy. Never mind.

**Comment by Alkarex** [comment]
@mathContao I suggest we address Blogotext separately so it is easier/cleaner to revert if needed. I am not a user, but it seems to be a self hosted system, so no new updates do not mean the instances are gone.

**Comment by math-GH** [comment]
> @mathContao I suggest we address Blogotext separately so it is easier/cleaner to revert if needed. I am not a user, but it seems to be a self hosted system, so no new updates do not mean the instances are gone.

as wished I cherry picked the commit and reverted it in this PR.
Separate PR that deletes blogotext: #3812

**Comment by seeknponder** [comment]
Total noob here, I got sent here by GPT looking for a system for tagging articles as they enter freshRss.
Is this plugin useful for that?
Is there a different system I could use for this purpose?

**Comment by Alkarex** [comment]
@seeknponder Please open a new issue instead. FreshRSS supports auto-tagging articles. You will find that in the tag management section.
