### PR TITLE
Better git error messages

### LINKED ISSUE #6483: Update process git error
### Discussed in https://github.com/FreshRSS/FreshRSS/discussions/5174

<div type='discussions-op-text'>

<sup>Originally posted by **zero77** March  5, 2023</sup>
**Describe the bug**
Before 1.21.0 stable release the dev updates worked correctly now they fail to update.
After clicking apply the following error is displayed and the update fails.

**To Reproduce**
1. Go to settings
2. Click on Apply under updates
3. Updates fail and show an error message

**Expected behavior**

**Screenshots**

Screenshot

**Environment information (please complete the following information):**
- Device: Firefox for Linux
- OS: Debian 11
- Browser: Firefox 102.8.0
- FreshRSS version: 1.21.0-dev
- Database version: [e.g. Mysql 5.7]
- PHP version: 7.4.33
- Installation type: Apache

**Additional context**

</div>

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/discussions/5174
fix https://github.com/FreshRSS/FreshRSS/issues/6483

### CODE REVIEW

File: app/Controllers/updateController.php [hunk 1]
```diff
@@ -10,20 +10,28 @@ public static function isGit(): bool {
...
 	public static function migrateToGitEdge(): bool {
-		$errorMessage = 'Error during git checkout to edge branch. Please change branch manually!';
-
 		if (!is_writable(FRESHRSS_PATH . '/.git/config')) {
-			throw new Minz_Exception($errorMessage);
+			throw new Minz_Exception('Error during git checkout: .git directory does not seem writeable! ' .
+				'Please git pull manually!');
+		}
+
+		exec('git -v', $output, $return);
```
Comment (Alkarex) [inline app/Controllers/updateController.php:23]: Improved compatibility in https://github.com/FreshRSS/FreshRSS/pull/6513
