### PR TITLE
fix: i18n for autom. dark mode config

### LINKED ISSUE #5164: Dark mode i18n of *no* and *auto*
We should remember to do the i18n of *no* and *auto*

_Originally posted by @Alkarex in https://github.com/FreshRSS/FreshRSS/pull/5002#discussion_r1125647009_

### PR DESCRIPTION
**Pull request by math-GH**
Closes #5164

Changes proposed in this pull request:

- i18n

How to test the feature manually:

1. go to `Display` config
2. see select of autom. dark mode

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

File: app/i18n/fr/conf.php [hunk 1]
```diff
@@ -32,7 +32,11 @@
 	),
 	'display' => array(
 		'_' => 'Affichage',
-		'darkMode' => 'Mode sombre automatique (bêta)',
+		'darkMode' => array(
+			'_' => 'Mode sombre automatique (bêta)',
+			'auto' => 'Auto',	// TODO
+			'no' => 'No',	// TODO
```
Comment (Alkarex) [inline app/i18n/fr/conf.php]:
```suggestion
			'auto' => 'Auto',	// IGNORE
			'no' => 'Non',
```

**Review by Alkarex — APPROVED** [review]
