### PR TITLE
Display sidebar dropdowns above if no space below

### LINKED ISSUE #7801: [Bug] Sidebar popup menu inaccessible at the bottom
### Describe the bug

When the popup menu is active scrolling is disabled on the sidebar, but that means that near the bottom it's inaccessible.

This may be a regression since I haven't noticed it before, but that could also be a coincidence.

Image

### To Reproduce

1. Have enough feeds or make the window sufficiently short that the sidebar is close to or touching the bottom
2. Click on the gear
3. The popup is inaccessible, fully or partially depending on prior scroll status

### Expected behavior

You can access the menu, preferably it'd pop up in the other direction but not preventing scrolling would probably suffice.

### FreshRSS version

084f9549804b98a266a8438614064f873fd07b07 (current edge)

### System information

- OS: Kubuntu 25.04
- Browser: Firefox 141

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Inverle**
Closes https://github.com/FreshRSS/FreshRSS/issues/7801

### CODE REVIEW

**Review by Alkarex — APPROVED** [review]

**Comment by Inverle** [comment]
I was testing without a navigation bar enabled, and noticed just now that it can still go under the navigation bar, so I have to make another PR

**Comment by Inverle** [comment]
#8336

File: p/scripts/main.js [hunk 1]
```diff
@@ -1106,6 +1108,27 @@ function init_column_categories() {
 					b.disabled = false;
 				}
 			}
+
+			window.addEventListener('hashchange', () => {
```
Comment (Inverle) [inline p/scripts/main.js:1112]: https://github.com/FreshRSS/FreshRSS/pull/8949
