### PR TITLE
fix preview

### LINKED ISSUE #4341: [BUG] CheckBox in main page is not running correctly.
**Describe the bug**
CheckBox (id: use_default_purge_options)  in main page is not running correctly.

**To Reproduce**
msedge_0WIEymdGTp

**Expected behavior**
xNqt4ap6qc

**Screenshots**

**Environment information (please complete the following information):**
- Device:  PC
- OS: WIN10
- Browser: Edge 101.0.1210.32
- FreshRSS version: 1.20.0-dev
- Database version: Mysql 5.7
- PHP version: PHP 8.0
- Installation type: General Installation

**Additional context**
I fixed it by loading category.js and executed archiving(). But the console showed a error when I loaded category.js. This is a small problem, and I'm not sure what the authors think of it.
屏幕截图 2022-05-01 141316

### PR DESCRIPTION
**Pull request by math-GH**
Closes the bug, that was made by #4226

Changes proposed in this pull request:

- extra.js will be loaded everywhere
- same name schema for functions that init after loading of DOM

How to test the feature manually:

1. go to normal view
2. open the sub menu of a feed
3. click on "manage"
4. the feed slider opens
5. click on the preview button
6. the preview overlay opens

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
lgtm

File: app/FreshRSS.php [hunk 1]
```diff
@@ -126,9 +126,7 @@ public static function loadStylesAndScripts() {
 			}
 		}
 		//Use prepend to insert before extensions. Added in reverse order.
-		if (Minz_Request::controllerName() !== 'index') {
-			FreshRSS_View::prependScript(Minz_Url::display('/scripts/extra.js?' . @filemtime(PUBLIC_PATH . '/scripts/extra.js')));
-		}
+		FreshRSS_View::prependScript(Minz_Url::display('/scripts/extra.js?' . @filemtime(PUBLIC_PATH . '/scripts/extra.js')));
```
Comment (Alkarex) [inline app/FreshRSS.php]: The idea of `extra.js` is to avoid loading a bunch of JS in our main view. Can that change be avoided?

Comment (math-GH) [reply app/FreshRSS.php]: Unfortunately not. Extra.js is needed for the feed configuration.
With https://github.com/FreshRSS/FreshRSS/pull/4226 the configuration slider is new in the main view.

To prevent to start the init_extra(), right after the script is loaded, I implemented:
```
if (!['normal', 'global', 'reader'].includes(context.current_view)) {
	init_extra();
}
```

Comment (math-GH) [reply app/FreshRSS.php]: ping @Alkarex

Comment (Alkarex) [reply app/FreshRSS.php]: I need to look at it again. I would very much like not to include `extra.js` all the time (that is the main point of having this distinct file)

**Comment by Alkarex** [comment]
Sorry for the delay, but there are multiple problems. For instance, the extra init is done multiple times, attaching events again many times:

image

It does not seem to be sufficient to fix https://github.com/FreshRSS/FreshRSS/issues/4341

The pop-up preview is hidden:
image

And the order of scripts is not ensured, resulting sometimes in errors
image

Does not work in non-ajax mode, e.g. http://localhost:8080/i/?c=subscription&a=feed&id=736&from=normal

I am trying to fix

**Comment by Alkarex** [comment]
@math-GH I have addressed a number of points https://github.com/FreshRSS/FreshRSS/pull/4291/commits/fb1a5305316cc51df0705d5b78b3250706f466a1 but I am away the rest of the day. I have a few remaining TODOs, but if you have time to double-check / test so far, that would be nice :-)

File: p/scripts/feed.js [hunk 2]
```diff
@@ -0,0 +1,231 @@
...
+// 		return false;
+// 	}
+
+// 	popup_working = true;
+
+// 	popup_txt.innerHTML = msg;
+
+// 	popup_txt.style.display = 'table-row';
+// 	popup.style.display = 'block';
+// }
```
Comment (Alkarex) [inline p/scripts/feed.js]: Will remove before merging. It does not looks like it has ever been used?

**Comment by math-GH** [comment]
Could you please check why the show-password-button does not show the password?

grafik

**Comment by Alkarex** [comment]
> Could you please check why the show-password-button does not show the password?

Ah, well spotted 🕵️ Will fix tomorrow

**Comment by BuleWhale** [comment]
> Could you please check why the show-password-button does not show the password?
> 
> grafik

need `extra.js`.
屏幕截图 2022-05-14 154137

屏幕截图 2022-05-14 154222

**Comment by BlueWhale235** [comment]
> Could you please check why the show-password-button does not show the password?
  
need `extra.js` and execute `init_password_observers()` when you open the slider window
屏幕截图 2022-05-14 154222

**Comment by BlueWhale235** [comment]
#4364  
New bugs. In `User queries` and `Extensions` page need `feed.js` in order to open slider window.  
**Fix**    
Need add  `FreshRSS_View::appendScript(Minz_Url::display('/scripts/feed.js?' . @filemtime(PUBLIC_PATH . '/scripts/feed.js')));`  in 
 `extensionController.php`  in 22 and  `configureController.php`  in 281.

**Comment by Alkarex** [comment]
Ready for new round of testing. Feedback welcome

**Review by Alkarex — APPROVED** [review]

**Comment by math-GH** [comment]
The purge policy checkbox in category does not work correct:
grafik

In the feed options it works fine

**Comment by Alkarex** [comment]
Good catch @math-GH , fixed

**Comment by math-GH** [comment]
> Could you please check why the show-password-button does not show the password?
> 
> grafik

Same issue in Statistics > Idle Feeds

**Comment by math-GH** [comment]
Also in Statistics > Idle Feeds:

The preview of "Article CSS selector on original website" does not open in a popup.

**Comment by Alkarex** [comment]
Good catch @math-GH , fixed https://github.com/FreshRSS/FreshRSS/pull/4291/commits/f40c9b949ee3bd0dc460b1e93855291f5d45f21a

**Comment by math-GH** [comment]
Now it looks fine for me too.

Thanks a lot to @Alkarex that you made this huge improvements.

**Comment by Alkarex** [comment]
I just found a last-minute bug, for e.g. `http://localhost/i/?c=subscription&id=735` , fixed https://github.com/FreshRSS/FreshRSS/pull/4291/commits/30440e2e3983069243d9981e574cff598cd5d3a1

**Comment by math-GH** [comment]
Found one more thing:
Page: Add a new feed
Option "Type of feed source" has no effect to the following form
grafik

**Comment by Alkarex** [comment]
Fixed! https://github.com/FreshRSS/FreshRSS/pull/4291/commits/9fb3e4ea03bca568cd6db442b5c869b7418de909
