### PR TITLE
fixed: Global view - Stick the article to the top when opened

### LINKED ISSUE #5073: [BUG] "Stick the article to the top when opened" does not work in global view
**Describe the bug**
"Stick the article to the top when opened" does not work in global view

**To Reproduce**
1. Configuration: Reading: check `Stick the article to the top when opened`
2. go to global view
3. open different articles
4. see that the opened article does not stick to the top

**Expected behavior**
Opened article sticks to the top

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0-dev

### PR DESCRIPTION
**Pull request by math-GH**
Closes #5073
Ref #2336

Changes proposed in this pull request:

- Javascript main.js

How to test the feature manually:

enable `Display `-> `Stick the article to the top when opened `

1. go to global view
2. open/close articles
3. the article sticks to the top

same behavior, when `Reading` -> `Show articles unfolded by default ` is enabled (Ref #2336)

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

File: p/scripts/main.js [hunk 1]
```diff
@@ -447,9 +447,7 @@ function toggleContent(new_active, old_active, skipping) {
 			// when skipping, this feels more natural if it’s not so near the top
 			new_pos -= document.body.clientHeight / 4;
 		}
-		if (relative_move) {
```
Comment (Alkarex) [inline p/scripts/main.js:450]: Isn't that used in normal view?

Comment (math-GH) [reply p/scripts/main.js:450]: see line 425: `const relative_move = context.current_view === 'global';`
