### PR TITLE
Fix API add category to multiple feeds

### LINKED ISSUE #7013: [Bug] GReader API: adding multiple feeds w/ categories
### Describe the bug

Hey, thank you for all your work. I noticed that when adding multiple feeds in a single request it's not possible to assign a category to both. For example, only the 2nd feed will be assigned to `testtag2` (the 1st feed will be uncategorized) given the following:

```
curl 'https://rss.mysite.com/api/greader.php/reader/api/0/subscription/edit' \
  --data-raw 'ac=subscribe&s=feed%2Fhttps%3A%2F%2Ffeeds.arstechnica.com%2Farstechnica%2Ftechnology-lab&t=ars+techlab&a=user%2F-%2Flabel%2Ftesttag1&s=feed%2Fhttps%3A%2F%2Ffeeds.arstechnica.com%2Farstechnica%2Fgadgets&t=ars+gadets&a=user%2F-%2Flabel%2Ftesttag2'
```

Same behavior if only one `a` param is sent.

### To Reproduce

cURL provided above

### Expected behavior

Ideally, the `a` (category) param would be treated as an array, similar to `$streamNames` and `$titles`. I suppose the next best thing would be to at least be able to apply a single category to all feeds in the request, though that feels a bit inconsistent.

### FreshRSS version

1.24.3

### Environment information

- Installation type: Docker

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/7013

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

File: p/api/greader.php [hunk 1]
```diff
@@ -366,11 +366,17 @@ private static function subscriptionList(): never {
 	}
 
 	/**
-	 * @param array<string> $streamNames
-	 * @param array<string> $titles
+	 * @param array<string> $streamNames StreamId(s) to operate on. The parameter may be repeated to edit multiple subscriptions at once
+	 * @param array<string> $titles Title(s) to use for the subscription(s). Each title is associated with the corresponding streamName
+	 * @param 'subscribe'|'unsubscribe'|'edit' $action
+	 * @param string $add StreamId to add the subscription(s) to (generally a category)
+	 * @param string $add StreamId to remove the subscription(s) from (generally a category)
```
Comment (bhj) [inline p/api/greader.php]: Should be `@param string $remove`

Comment (Alkarex) [reply p/api/greader.php]: Thanks! https://github.com/FreshRSS/FreshRSS/pull/7017/commits/52a98484db5d3ff186ee38957ce3dfebbcb56a83

File: p/api/greader.php [hunk 2]
```diff
@@ -426,7 +432,7 @@ private static function subscriptionEdit(array $streamNames, array $titles, stri
 						if ($feedId <= 0) {
 							$http_auth = '';
 							try {
-								$feed = FreshRSS_feed_Controller::addFeed($streamUrl, $title, $addCatId, $c_name, $http_auth);
+								$feed = FreshRSS_feed_Controller::addFeed($streamUrl, $title, $addCatId, '', $http_auth);
```
Comment (ColonelMoutarde) [inline p/api/greader.php]: Unused local variable 'feed'. The value of the variable is overwritten
