### PR TITLE
Fix #3835: theme switcher broken when theme is not available

### LINKED ISSUE #3835: [BUG] theme switcher unusable if folder not exists
**Describe the bug**
If the folder of the currently selected theme gets deleted, the switcher gui is rendered as completely empty frame and without navigation options (left/right).
After the folder is copied back or the language is switched in the gui (as reported [here](https://github.com/FreshRSS/FreshRSS/issues/3670#issue-914454450)), the theme switcher is usable again.

**To Reproduce**
1. Delete or rename the folder of the current theme.
2. Open Configuration->Display

**Expected behavior**
Theme switcher displayed and usable.

**Environment information (please complete the following information):**
 - Device: Smartphone, PC
 - OS: Android, openSuse
 - Browser: Firefor (Android/Linux, current version)
 - FreshRSS version: 1.18 and later
 - Database version: [e.g. Mysql 5.7]
 - PHP version: 7.3.29
 - Installation type: Raspi

### PR DESCRIPTION
**Pull request by math-GH**
Closes #3835

Changes proposed in this pull request:
- an error message is display when the theme is not available
- user can use the prev-button to choose an existing theme
- when user does not chose another theme and clicks on safe, than it safes "Origine" theme.

grafik

How to test the feature manually:
1. delete/rename the chosen theme folder in `p/themes`
2. go to settings -> display
3. see the red error message

Pull request checklist:
- [x] clear commit messages
- [x] code manually tested
- [x] i18n: English
- [x] i18n German
- [ ] i18n French
- other i18n: please give me a translation

### CODE REVIEW

File: app/i18n/en/conf.php [hunk 1]
```diff
@@ -39,6 +39,7 @@
 		),
 		'show_nav_buttons' => 'Show the navigation buttons',
 		'theme' => 'Theme',
+		'theme_not_available' => 'Error. The theme "%s" is not available anymore. Please chose another theme.',
```
Comment (Frenzie) [inline app/i18n/en/conf.php]:
```suggestion
		'theme_not_available' => 'The "%s" theme is not available anymore. Please choose another theme.',
```

Comment (math-GH) [reply app/i18n/en/conf.php]: fixed it

**Review by Frenzie — APPROVED** [review]
No further comments, lgtm :+1:

File: app/i18n/nl/conf.php [hunk 2]
```diff
@@ -39,6 +39,7 @@
 		),
 		'show_nav_buttons' => 'Toon navigatieknoppen',
 		'theme' => 'Thema',
+		'theme_not_available' => 'The "%s" theme is not available anymore. Please choose another theme.', // TODO - Translation
```
Comment (Frenzie) [inline app/i18n/nl/conf.php]: Oh right, might as well add the Dutch translation as part of the PR.
```suggestion
		'theme_not_available' => 'Het "%s" thema is niet meer beschikbaar. Kies een ander thema.',Translation
```

Comment (math-GH) [reply app/i18n/nl/conf.php]: thanks. done.

**Comment by math-GH** [comment]
Who could do the French translation?

**Comment by Frenzie** [comment]
That would be something like:
```
Le thème "%s" n'est plus disponible. Veuillez choisir un autre thème.
```

But @aledeg and @Alkarex might still find something wrong with that.
