### PR TITLE
Fix repartitionAction

### LINKED ISSUE #5227: [BUG] Fatal error:  Uncaught TypeError: FreshRSS_FeedDAO::searchById(): Argument
**Describe the bug**
```
Fatal error:  Uncaught TypeError: FreshRSS_FeedDAO::searchById(): Argument #1 ($id) must be of type int, null given, called in foo\bar\app\Controllers\statsController.php on line 208 and defined in foo\bar\app\Models\FeedDAO.php:287
Stack trace:
#0 foo\bar\app\Controllers\statsController.php(208): FreshRSS_FeedDAO->searchById(NULL)
#1 foo\bar\lib\Minz\Dispatcher.php(119): FreshRSS_stats_Controller->repartitionAction()
#2 foo\bar\lib\Minz\Dispatcher.php(48): Minz_Dispatcher->launchAction('repartitionActi...')
#3 foo\bar\lib\Minz\FrontController.php(58): Minz_Dispatcher->run()
#4 foo\bar\p\i\index.php(57): Minz_FrontController->run()
#5 {main}
  thrown in foo\bar\app\Models\FeedDAO.php on line 287
```

**To Reproduce**
1. Go to `Articles repartition`
grafik
2. see the error

**Expected behavior**
see the content of `Articles repartition` without an error

**Environment information (please complete the following information):**
- FreshRSS version: current 1.21.1-dev

### PR DESCRIPTION
**Pull request by Alkarex**
Fix https://github.com/FreshRSS/FreshRSS/issues/5227

### CODE REVIEW

File: app/Controllers/statsController.php [hunk 1]
```diff
@@ -202,10 +202,13 @@ public function repartitionAction(): void {
...
 
-		$id = Minz_Request::param('id', null);
+		$id = (int)(Minz_Request::param('id'));
+		if ($id === 0) {
+			$id = null;
+		}
 
 		$this->view->categories 	= $categoryDAO->listCategories();
-		$this->view->feed 			= $feedDAO->searchById($id);
+		$this->view->feed 			= $id === null ? null : $feedDAO->searchById($id);
```
Comment (Alkarex) [inline app/Controllers/statsController.php:211]: That was the main error

**Comment by Alkarex** [comment]
Contributes to https://github.com/FreshRSS/FreshRSS/issues/4112

**Review by math-GH — APPROVED** [review]
