### PR TITLE
Fix user self-deletion

### LINKED ISSUE #7625: [Bug] Deleting account doesn't work
### Describe the bug

After typing in password and clicking `Remove`

Image

This prompt gets shown:

Image

After clicking OK, nothing happens and no request gets sent.

### To Reproduce

1. Create new test user account
2. Log into the account
3. Go into Profile
4. Try deleting account and see nothing happens

### Expected behavior

The account should get deleted after clicking OK

### FreshRSS version

1.26.3-dev

### System information

-

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Inverle**
Closes #7625

### CODE REVIEW

File: p/scripts/extra.js [hunk 1]
```diff
@@ -70,13 +65,15 @@ function init_crypto_form() {
...
 							openNotification('Crypto error!', 'bad');
 						} else {
 							crypto_form.removeEventListener('submit', crypto_form.onsubmit);
 							crypto_form.submit();
 						}
 					} catch (ex) {
+						submit_button.disabled = false;
 						openNotification('Crypto exception! ' + ex, 'bad');
 					}
 				}
```
Comment (Alkarex) [inline p/scripts/extra.js]:
```suggestion
						if (!s || !c) {
							openNotification('Crypto error!', 'bad');
						} else {
							crypto_form.removeEventListener('submit', crypto_form.onsubmit);
							crypto_form.submit();
						}
					} catch (ex) {
						openNotification('Crypto exception! ' + ex, 'bad');
					}
				}
				submit_button.disabled = false;
```

A single `submit_button.disabled = false;` should be sufficient, just after the `else`

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
Could catch 👍🏻 
I have not checked for how long this has been broken

File: p/scripts/extra.js (hunk 1 above)
Comment (Inverle) [reply p/scripts/extra.js]: You're right

**Comment by Inverle** [comment]
Maybe since 5ca961b?
