### PR TITLE
fix: space key opens empty tab

### LINKED ISSUE #4579: [BUG] Space key opens an empty tab
When you press the `space` key somewhere an empty tab will be opened

**Expected behavior**
no tab. 
The defined shortcut action.

**Environment information (please complete the following information):**

- FreshRSS version: 1.19.2 + 1.20.0-dev

### PR DESCRIPTION
**Pull request by math-GH**
Closes #4579

Changes proposed in this pull request:

- JavaScript

How to test the feature manually:

1. check if "space" is set as shortcut for the "open website"
2. press space key every where (nothing special will happen, maybe the window will scroll down)
3. press space key, when an article is focused: it will open a new tab with the link

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

File: p/scripts/main.js [hunk 1]
```diff
@@ -1001,12 +1001,16 @@ function init_shortcuts() {
...
 			}
-			const newWindow = window.open();
-			if (newWindow) {
-				newWindow.opener = null;
-				newWindow.location = document.querySelector('.flux.current a.go_website').href;
+
+			const link_go_website = document.querySelector('.flux.current a.go_website');
+			if (link_go_website) {
+				const newWindow = window.open();
+				if (newWindow) {
```
Comment (Frenzie) [inline p/scripts/main.js]: I'd personally be more inclined to write it more like this as I think that's slightly more legible but I suppose ymmv. :-)
```suggestion
			const link_go_website = document.querySelector('.flux.current a.go_website');
			const newWindow = window.open();
			if (link_go_website && newWindow) {
```

**Review by Frenzie — APPROVED** [review]
