### PR TITLE
Back-compatibility cURL 7.51

### LINKED ISSUE #7381: [Bug] After updated to FreshRSS 1.26.0 I can no longer add new feeds
### Describe the bug

Hello everyone,
I installed FreshRSS 1.25.0 on a shared server (mysql: 8.0 + php 8.2.9) and when I see the new version I performed the update to 1.26.0 by FTP.
Everything seems to work correctly except the impossibility to add new feeds. If I enter the subscription screen I find only the button to add new categories and in the bottom part of screen I cannot confirm in any way the subscription to a new feed. Did I miss something? Thanks

Image

### To Reproduce

1. Go to 'Subscription page'
2. Add URL of Feed
3. Scroll down but not confirm button are present

### Expected behavior

_No response_

### FreshRSS version

1.26.0

### System information

- Database version: MySQL 8
- PHP version: PHP 8.2.9
- Installation type: lamp + ftp
- Browser: Firefox 135

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/7381
And add cURL version to system info.
Do not require a specific version of cURL for now, but maybe later.

### CODE REVIEW

**Comment by Alkarex** [comment]
image

**Comment by Alkarex** [comment]
And help welcome to add a warning during install as well as in setup check for cURL versions that are older than 7.52

**Review by Frenzie — APPROVED** [review]
Feels potentially slightly dangerous

**Comment by Alkarex** [comment]
What is your main worry, @Frenzie ?

**Comment by Frenzie** [comment]
Other random small things like that. :-)

**Comment by Alkarex** [comment]
image

File: app/i18n/it/index.php [hunk 1]
```diff
@@ -20,6 +20,7 @@
 				'browser' => 'Browser',	// IGNORE
 				'database' => 'Database',	// IGNORE
 				'server_software' => 'Software server',
+				'version_curl' => 'cURL version',	// TODO
```
Comment (UserRoot-Luca) [inline app/i18n/it/index.php]:
```suggestion
				'version_curl' => 'Versione cURL',
```
